### ISSUE TITLE
EOF error sometimes gets triggered due to the timeouts being to aggressive on the consumer side

### ISSUE THREAD

**Issue by mrakgr** [Lumerin-protocol/Morpheus-Lumerin-Node#304]
![image](https://github.com/user-attachments/assets/5183c678-216a-407c-9932-3e9516dac7dd)

You can see how it looks here. It happened today and a few times in the past on startup while creating a session. 

![image](https://github.com/user-attachments/assets/9171dfc2-d238-48f5-8696-ee95976666cf)

I tried debugging it, and it's easy to trigger this error by placing breakpoints which introduce delays. But once the breakpoints are removed the error goes away. So, what I think is happening is that the connection gets closed on the consumer side if the proxy server waits too long to read it. Maybe you could check if the request timeouts on the consumer side are set too aggressively?

**Comment by abs2023** [comment]
@mrakgr - we have updated the wait states and cycle times for timeouts. Please take a look at v 1.2.0 released last night and it should be better when there's a delay coming back from the LLM server (we found this when running video or image prompt inferences). had to keep checking if the provider was still "up" and then wait up to 2.5 minutes before timing out.

**Comment by abs2023** [comment]
What version are you running?

**Comment by mrakgr** [comment]
![image](https://github.com/user-attachments/assets/b0de557b-7c50-445f-a800-b626dd851044)

Here is one right near the bottom.

![image](https://github.com/user-attachments/assets/2cb612ba-e27a-4782-acf6-440a79bad63e)

And I forgot to switch to the main branch and used the dev branch by accident due to moving to a new machine. I'll try the main branch.

**Comment by mrakgr** [comment]
![image](https://github.com/user-attachments/assets/53300b6c-0668-426f-bbb2-4037ce2888b8)
It happens when I move to the main branch too. Who knows, I was just speculating that this error was due to the delays, it could be something else.

**Comment by abs2023** [comment]
I think that is one of the public ethnodes  178.62.3.19 that may not be responding or timing out and shouldn't be a concern as we use a few of them.  
If you use your own Infura/alchemy ethnode (edit .env ... update the ETH_NODE_ADDRESS= to https:///<your alchemy or infura endpoint> and also make sure ETH_NODE_USE_SUBSCRIPTIONS=false (so that you force https polling instead of subscriptions) 

Also, one other thing to note about the branches...`dev` (of course) is volatile, `test` is a little less volatile and used for final QA before being promoted to `main` that we then PR back to MorphusAIs origin.  There really is no difference other than maturity of the code differentiating between mainnet and testnet (any of the three branches can be used on the different chains, you just have to update the .env files)...so, as you're moving back and forth, just be aware.  I've included extra "helper" .env.example files with testnet and mainnet blocks (mainnet on all published branches by default now) that you can (un)comment based on needs. 

Anyway, i don't think the EOF is a big issue, unless you're seeing other unexpected behavior in the proxy-router operation.  Let us know if that's the case (oh, and updated logging and informational details are coming in the next few weeks that should help diagnostics and such)

**Comment by mrakgr** [comment]
![image](https://github.com/user-attachments/assets/96402172-54ba-49c0-9742-4feae5e01987)
Setting `ETH_NODE_USE_SUBSCRIPTIONS=false` didn't help, but I agree that this issue isn't high priority. Should the `ETH_NODE_ADDRESS` really be https instead of wss? I'll try that later.

**Comment by abs2023** [comment]
We have 3 options for querying the eth network 
1. Leave .env entries blank and we handle it with public nodes automatically (http polling) 
2. Your own node using http (`https://infura.io/api...etc....`) where you should ALSO set `ETH_NODE_USE_SUBSCRIPTIONS=false`
3. Or Your own node using wss (`wss://infura...etc...`) where you should set `ETH_NODE_USE_SUBSCRIPTIONS=true`  

The last option was actually where we started, but options 1 and 2 are better because they're not requiring a constant connection which sometimes can break based on network.  So Option 1 is pretty good for most cases, Option 2 if you really want to do your own thing...3 if you like WSS

**Comment by mrakgr** [comment]
![image](https://github.com/user-attachments/assets/a63d953e-5a5e-49cb-9d71-5428da6cb2e4)
![image](https://github.com/user-attachments/assets/09cdf2d3-80df-4520-a19f-cdf9791c7d8b)

I get the same error with https and `ETH_NODE_USE_SUBSCRIPTIONS=false`. No luck it seems.

One new things I've noticed is this:

```
2024-12-06T17:35:04.85563928    WARN    PROVIDER_CHECK  provider 0xEaaa28d9b875926e7511e2cE4Bdc93658c4269bc is not reachable from localhost by address 64.21.190.98:3334: provider request failed: code: 500, msg: <nil>, error: failed to connect to provider: dial tcp 64.21.190.98:3334: connect: connection refused
```

This wasn't in the previous version. Why is it having trouble reaching itself during startup?

**Comment by abs2023** [comment]
That IP address (178.62.3.19) comes back as digital ocean owned address (the name server recognizes it, but there's no host name).  If you're behind a load balancer (and hosted in digital ocean)  that could be health check coming from that (src addr has high ports).  I see this when i'm running in AWS with the proxy behind an ALB ... the ALB health checker keeps trying to connect, doesn't talk the way it expects and then shuts the connection down).  If that's the case, then no trouble found. 

The second "new item" is part of config checker that we've added to the proxy router on startup to make troubleshooting and "are you ready to go" a little easier... 

It checks your config, models, Rating config, accessibility, etc... of the proxy-router startup.  If you look at your log stream above, it looks like your MODEL_LOADER isn't loading right (please check it against the latest format in the docs/models-config.json.md doc) ... it is backward compatible with the old version of the json file, but looks like this is not coming through (and likely an issue on your other ticket) 

So...all that to say...all the startup checks look like they're good (and i was able to telnet to that :3334 endpoint just to check that it's talking) from outside.  It says connection refused, so if that ip address is a load balancer, do you allow inbound connections from the server itself? (it's using the IP not the localhost designator) (two lines above shows that it's listening). 

We're continuing to improve the startup checker (and will also have some API checks as well that will help ferret out config issues faster).
